/*
 * generated by Xtext 2.25.0
 */
package org.xtext.ensias.yjdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractYJDslScopeProvider extends DelegatingScopeProvider {
}
