/*
 * generated by Xtext 2.25.0
 */
package org.xtext.ensias.yjdsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.ensias.yjdsl.parser.antlr.internal.InternalYJDslParser;
import org.xtext.ensias.yjdsl.services.YJDslGrammarAccess;

public class YJDslParser extends AbstractAntlrParser {

	@Inject
	private YJDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalYJDslParser createParser(XtextTokenStream stream) {
		return new InternalYJDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Application";
	}

	public YJDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(YJDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
