/*
 * generated by Xtext 2.25.0
 */
package org.xtext.ensias.yjdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class YJDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/ensias/yjdsl/parser/antlr/internal/InternalYJDsl.tokens");
	}
}
