/*
 * generated by Xtext 2.25.0
 */
package org.xtext.ensias.yjdsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class YJDslStandaloneSetup extends YJDslStandaloneSetupGenerated {

	public static void doSetup() {
		new YJDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
