/*
 * generated by Xtext 2.25.0
 */
package org.xtext.ensias.yjdsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class YJDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ApplicationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ensias.yjdsl.YJDsl.Application");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cApplicationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cConfigKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cConfigAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cConfigConfigParserRuleCall_3_0 = (RuleCall)cConfigAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cEntityKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cEntityAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cEntityEntityParserRuleCall_4_2_0 = (RuleCall)cEntityAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cEntityAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cEntityEntityParserRuleCall_4_3_1_0 = (RuleCall)cEntityAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Application returns jdl::Application:
		//    'Application'
		//    '{'
		//        'config' config=Config
		//        ('entity' '{' entity+=Entity ( "," entity+=Entity)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Application'
		//'{'
		//    'config' config=Config
		//    ('entity' '{' entity+=Entity ( "," entity+=Entity)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Application'
		public Keyword getApplicationKeyword_0() { return cApplicationKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'config'
		public Keyword getConfigKeyword_2() { return cConfigKeyword_2; }
		
		//config=Config
		public Assignment getConfigAssignment_3() { return cConfigAssignment_3; }
		
		//Config
		public RuleCall getConfigConfigParserRuleCall_3_0() { return cConfigConfigParserRuleCall_3_0; }
		
		//('entity' '{' entity+=Entity ( "," entity+=Entity)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'entity'
		public Keyword getEntityKeyword_4_0() { return cEntityKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//entity+=Entity
		public Assignment getEntityAssignment_4_2() { return cEntityAssignment_4_2; }
		
		//Entity
		public RuleCall getEntityEntityParserRuleCall_4_2_0() { return cEntityEntityParserRuleCall_4_2_0; }
		
		//( "," entity+=Entity)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//entity+=Entity
		public Assignment getEntityAssignment_4_3_1() { return cEntityAssignment_4_3_1; }
		
		//Entity
		public RuleCall getEntityEntityParserRuleCall_4_3_1_0() { return cEntityEntityParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ConfigElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ensias.yjdsl.YJDsl.Config");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cConfigAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cConfigKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cBaseNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cBaseNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cBaseNameEStringParserRuleCall_3_1_0 = (RuleCall)cBaseNameAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAppTypeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cAppTypeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cAppTypeEStringParserRuleCall_4_1_0 = (RuleCall)cAppTypeAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cPackageNameKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cPackageNameAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cPackageNameEStringParserRuleCall_5_1_0 = (RuleCall)cPackageNameAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cDataBaseTypeKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cDataBaseTypeAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cDataBaseTypeEStringParserRuleCall_6_1_0 = (RuleCall)cDataBaseTypeAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Config returns jdl::Config:
		//    {jdl::Config}
		//    'Config'
		//    '{'
		//        ('baseName' baseName=EString)?
		//        ('appType' appType=EString)?
		//        ('packageName' packageName=EString)?
		//        ('dataBaseType' dataBaseType=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{jdl::Config}
		//'Config'
		//'{'
		//    ('baseName' baseName=EString)?
		//    ('appType' appType=EString)?
		//    ('packageName' packageName=EString)?
		//    ('dataBaseType' dataBaseType=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{jdl::Config}
		public Action getConfigAction_0() { return cConfigAction_0; }
		
		//'Config'
		public Keyword getConfigKeyword_1() { return cConfigKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('baseName' baseName=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'baseName'
		public Keyword getBaseNameKeyword_3_0() { return cBaseNameKeyword_3_0; }
		
		//baseName=EString
		public Assignment getBaseNameAssignment_3_1() { return cBaseNameAssignment_3_1; }
		
		//EString
		public RuleCall getBaseNameEStringParserRuleCall_3_1_0() { return cBaseNameEStringParserRuleCall_3_1_0; }
		
		//('appType' appType=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'appType'
		public Keyword getAppTypeKeyword_4_0() { return cAppTypeKeyword_4_0; }
		
		//appType=EString
		public Assignment getAppTypeAssignment_4_1() { return cAppTypeAssignment_4_1; }
		
		//EString
		public RuleCall getAppTypeEStringParserRuleCall_4_1_0() { return cAppTypeEStringParserRuleCall_4_1_0; }
		
		//('packageName' packageName=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'packageName'
		public Keyword getPackageNameKeyword_5_0() { return cPackageNameKeyword_5_0; }
		
		//packageName=EString
		public Assignment getPackageNameAssignment_5_1() { return cPackageNameAssignment_5_1; }
		
		//EString
		public RuleCall getPackageNameEStringParserRuleCall_5_1_0() { return cPackageNameEStringParserRuleCall_5_1_0; }
		
		//('dataBaseType' dataBaseType=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'dataBaseType'
		public Keyword getDataBaseTypeKeyword_6_0() { return cDataBaseTypeKeyword_6_0; }
		
		//dataBaseType=EString
		public Assignment getDataBaseTypeAssignment_6_1() { return cDataBaseTypeAssignment_6_1; }
		
		//EString
		public RuleCall getDataBaseTypeEStringParserRuleCall_6_1_0() { return cDataBaseTypeEStringParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class EntityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ensias.yjdsl.YJDsl.Entity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEntityAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cEntityKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Entity returns jdl::Entity:
		//    {jdl::Entity}
		//    'Entity'
		//    name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{jdl::Entity}
		//'Entity'
		//name=EString
		public Group getGroup() { return cGroup; }
		
		//{jdl::Entity}
		public Action getEntityAction_0() { return cEntityAction_0; }
		
		//'Entity'
		public Keyword getEntityKeyword_1() { return cEntityKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ensias.yjdsl.YJDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	
	
	private final ApplicationElements pApplication;
	private final ConfigElements pConfig;
	private final EntityElements pEntity;
	private final EStringElements pEString;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public YJDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pApplication = new ApplicationElements();
		this.pConfig = new ConfigElements();
		this.pEntity = new EntityElements();
		this.pEString = new EStringElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.ensias.yjdsl.YJDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Application returns jdl::Application:
	//    'Application'
	//    '{'
	//        'config' config=Config
	//        ('entity' '{' entity+=Entity ( "," entity+=Entity)* '}' )?
	//    '}';
	public ApplicationElements getApplicationAccess() {
		return pApplication;
	}
	
	public ParserRule getApplicationRule() {
		return getApplicationAccess().getRule();
	}
	
	//Config returns jdl::Config:
	//    {jdl::Config}
	//    'Config'
	//    '{'
	//        ('baseName' baseName=EString)?
	//        ('appType' appType=EString)?
	//        ('packageName' packageName=EString)?
	//        ('dataBaseType' dataBaseType=EString)?
	//    '}';
	public ConfigElements getConfigAccess() {
		return pConfig;
	}
	
	public ParserRule getConfigRule() {
		return getConfigAccess().getRule();
	}
	
	//Entity returns jdl::Entity:
	//    {jdl::Entity}
	//    'Entity'
	//    name=EString;
	public EntityElements getEntityAccess() {
		return pEntity;
	}
	
	public ParserRule getEntityRule() {
		return getEntityAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
